.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bhtune-opc-search-index-refresh 1  "bhtune-opc-search-index-refresh "
.SH NAME
bhtune\-opc\-search\-index\-refresh \- Start or coalesce a persistent namespace\-index refresh
.SH SYNOPSIS
\fBbhtune\-opc\-search\-index\-refresh\fR [\fB\-\-bridge\-host\fR] [\fB\-\-server\fR] [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Start or coalesce a persistent namespace\-index refresh
.SH OPTIONS
.TP
\fB\-\-bridge\-host\fR \fI<BRIDGE_HOST>\fR

.TP
\fB\-\-server\fR \fI<SERVER>\fR

.TP
\fB\-\-force\fR
Start a refresh even when the active index is already current
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
