.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bhtune-opc-write 1  "bhtune-opc-write "
.SH NAME
bhtune\-opc\-write \- Write a value to one tag
.SH SYNOPSIS
\fBbhtune\-opc\-write\fR [\fB\-\-bridge\-host\fR] [\fB\-\-server\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fITAG\fR> <\fIVALUE\fR>
.SH DESCRIPTION
Write a value to one tag
.SH OPTIONS
.TP
\fB\-\-bridge\-host\fR \fI<BRIDGE_HOST>\fR

.TP
\fB\-\-server\fR \fI<SERVER>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITAG\fR>

.TP
<\fIVALUE\fR>

