.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bhtune-template-show 1  "bhtune-template-show "
.SH NAME
bhtune\-template\-show \- Show one template\*(Aqs full detail as JSON
.SH SYNOPSIS
\fBbhtune\-template\-show\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR>
.SH DESCRIPTION
Show one template\*(Aqs full detail as JSON
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

