.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bhtune-opc-browse 1  "bhtune-opc-browse "
.SH NAME
bhtune\-opc\-browse \- Browse tags under a path (empty for the top level)
.SH SYNOPSIS
\fBbhtune\-opc\-browse\fR [\fB\-\-bridge\-host\fR] [\fB\-\-server\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR]
.SH DESCRIPTION
Browse tags under a path (empty for the top level)
.SH OPTIONS
.TP
\fB\-\-bridge\-host\fR \fI<BRIDGE_HOST>\fR

.TP
\fB\-\-server\fR \fI<SERVER>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: ]

