.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bhtune-template-list 1  "bhtune-template-list "
.SH NAME
bhtune\-template\-list \- List every template (built\-in and user\-imported)
.SH SYNOPSIS
\fBbhtune\-template\-list\fR [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
List every template (built\-in and user\-imported)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
