.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bhtune-opc-search-index-status 1  "bhtune-opc-search-index-status "
.SH NAME
bhtune\-opc\-search\-index\-status \- Show persistent namespace\-index status
.SH SYNOPSIS
\fBbhtune\-opc\-search\-index\-status\fR [\fB\-\-bridge\-host\fR] [\fB\-\-server\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Show persistent namespace\-index status
.SH OPTIONS
.TP
\fB\-\-bridge\-host\fR \fI<BRIDGE_HOST>\fR

.TP
\fB\-\-server\fR \fI<SERVER>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
