/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe. */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List tune runs, filtered and paginated.
     * @description `GET /api/runs` -- newest-started-first, filtered by every present [`RunListQuery`] field,
     *     one [`Pagination`] page at a time.
     */
    get: operations["list_runs"];
    put?: never;
    /**
     * Start a new tune run.
     * @description `POST /api/runs` -- runs `prepare()` (template lookup, tag derivation, backend connect,
     *     and the `tune_runs` insert) inline and returns as soon as that succeeds, having already
     *     `tokio::spawn`ed the actual polling/tuning phase in the background. `201 Created` carries
     *     the same [`RunDetailResponse`] `GET /api/runs/{id}` would show for this run at this
     *     instant (almost certainly still `outcome: "running"`) -- poll that endpoint, or use
     *     `POST /api/runs/{id}/cancel`, to follow the run to completion.
     *
     *     `409 Conflict` if another run is already active: v1 allows only one at a time (see
     *     `crate::active_run`).
     */
    post: operations["start_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch one run's full detail.
     * @description `GET /api/runs/{id}` -- 404 if no run has that id.
     */
    get: operations["show_run"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request cancellation of a run, exactly as if Ctrl+C had been pressed against an
     *     equivalent CLI-driven run.
     * @description `POST /api/runs/{id}/cancel` -- `404` if no run has that id; otherwise always `204`,
     *     whether or not the run was actually active at the moment this was called (a run that
     *     already finished simply has nothing left to cancel). Cancellation is asynchronous: the
     *     run's background task still has to observe it, stop polling, and run its restore --
     *     `GET /api/runs/{id}` shows the eventual outcome.
     */
    post: operations["cancel_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List every stored template.
     * @description `GET /api/templates` -- every stored template (built-in, catalog, and user-created
     *     alike), ordered by name, for a template picker.
     */
    get: operations["list_templates"];
    put?: never;
    /**
     * Create a new, user-owned template.
     * @description `POST /api/templates` -- 400 if [`DcsTemplate::validate`] rejects the body, 409 if a
     *     template with the same name already exists.
     */
    post: operations["create_template"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch one template by name.
     * @description `GET /api/templates/{name}` -- 404 if no template has that name.
     */
    get: operations["get_template"];
    put?: never;
    post?: never;
    /**
     * Delete a template by name.
     * @description `DELETE /api/templates/{name}` -- 404 if no template has that name, 409 if it is still
     *     referenced by a saved loop (`bhtune_db::DbError::TemplateInUse`, mapped by
     *     `From<DbError> for ApiError`).
     */
    delete: operations["delete_template"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Direct-acting (increasing MV increases PV) or Reverse-acting (increasing MV decreases
     *     PV).
     * @enum {string}
     */
    ControllerDirection: "direct" | "reverse";
    /**
     * @description A PID controller structure. Discriminants double as the column index into the
     *     tuning-constant matrices in [`crate::constants`].
     * @enum {string}
     */
    ControllerType: "p" | "pi" | "pid";
    /** @description One DCS/PLC vendor's conventions. */
    DcsTemplate: {
      /**
       * @description The raw value a Controller Direction tag holds when the controller is Direct
       *     acting; see [`crate::direction::ControllerDirection::from_raw_tag_value`].
       */
      controller_action_direct_value: string;
      controller_direction_suffix: string;
      controller_mode_suffix: string;
      derivative_constant_suffix: string;
      derivative_type: components["schemas"]["DerivativeType"];
      derivative_unit: components["schemas"]["TimeUnit"];
      /** @description Free-text description of the control system this template targets. */
      description?: string | null;
      integral_constant_suffix: string;
      integral_type: components["schemas"]["IntegralType"];
      integral_unit: components["schemas"]["TimeUnit"];
      lower_mv_range_suffix: string;
      lower_pv_range_suffix: string;
      manipulated_variable_suffix: string;
      /**
       * @description The raw value a Mode Attribute tag holds when in "Program" mode (permits external
       *     OPC writes). `None` when the DCS has no mode-attribute concept.
       */
      mode_attribute_program_value?: string | null;
      mode_attribute_suffix: string;
      mode_auto_value: string;
      /** @description The DCS-specific raw values a Mode tag holds for Manual/Auto. */
      mode_manual_value: string;
      name: string;
      /**
       * @description OPC item-name suffixes, combined with a PV tag's path prefix by
       *     [`crate::tags::derive_tag`] to fill in the rest of the tag set. An empty suffix
       *     means the corresponding tag is not applicable for this DCS (e.g. some DCS families
       *     have no mode-attribute concept).
       */
      process_variable_suffix: string;
      proportional_constant_suffix: string;
      proportional_type: components["schemas"]["ProportionalType"];
      /**
       * @description If true, the controller mode is switched back to its original mode (e.g.
       *     Auto/Cascade) after a completed MRFT test. Has no effect if the loop was already in
       *     Manual at test start.
       */
      revert_mode: boolean;
      setpoint_variable_suffix: string;
      /**
       * @description Citation for where this mapping came from (a manual, a field deployment).
       *     Provenance, not a correctness guarantee -- there is deliberately no separate
       *     "verified" trust field; everything accepted into the catalog is treated as verified,
       *     and real mapping errors are fixed as bugs when they surface.
       */
      source?: string | null;
      upper_mv_range_suffix: string;
      upper_pv_range_suffix: string;
      /**
       * @description DCS/PLC releases this mapping is known to apply to (e.g. `["R5", "R6"]`), in each
       *     vendor's own version-naming convention rather than a normalized scheme. A newer
       *     release that changes tag conventions gets its *own* template entry with its own
       *     `name` and `versions` list -- never an edit to this one in place, since sites still
       *     running the older release depend on the existing mapping (see
       *     `docs/dcs-templates.md`). May be empty for a contribution whose version coverage
       *     isn't yet known; `name` is what makes a template unique, not `versions`.
       */
      versions?: string[];
    };
    /**
     * @description How a DCS expresses the derivative term.
     * @enum {string}
     */
    DerivativeType: "derivative_time" | "derivative_gain";
    /**
     * @description The JSON body of every non-2xx response: `{"error": "<message>"}`. `pub`/`ToSchema` so
     *     every fallible `#[utoipa::path]` response can reference it (`body = ErrorBody`) and the
     *     generated OpenAPI spec -- and therefore the generated frontend TS client -- accurately
     *     types error bodies instead of `content?: never`.
     */
    ErrorBody: {
      error: string;
    };
    Health: {
      status: string;
    };
    /**
     * @description Local projection of [`bhtune_db::models::TuneRunInitialReadings`] -- see this module's
     *     doc comment for why every JSON-facing type here is its own projection rather than a
     *     `Serialize` impl on the `bhtune-db` row type.
     */
    InitialReadingsResponse: {
      controller_direction: components["schemas"]["ControllerDirection"];
      mode_attribute_raw?: string | null;
      mode_raw?: string | null;
      /** Format: float */
      mv_ini: number;
      /** Format: float */
      mv_range_high: number;
      /** Format: float */
      mv_range_low: number;
      /** Format: float */
      pv_ini: number;
      /** Format: float */
      pv_range_high: number;
      /** Format: float */
      pv_range_low: number;
      /** Format: float */
      setpoint_ini?: number | null;
    };
    /**
     * @description How a DCS expresses the integral term.
     * @enum {string}
     */
    IntegralType: "reset_time" | "reset_rate" | "reset_gain";
    LoopConfig: {
      controller_type: components["schemas"]["ControllerType"];
      /**
       * Format: int32
       * @description Pre/post-test recording padding, in seconds. PV is still read and recorded during
       *     this period; no switch evaluation happens.
       */
      mrft_delay_secs: number;
      /** Format: int32 */
      noise_protection_secs: number;
      /** Format: int32 */
      num_cycles_count: number;
      /** Format: int32 */
      num_cycles_skip: number;
      process_type: components["schemas"]["ProcessType"];
      /**
       * Format: float
       * @description Relay amplitude as a percentage of the MV range. Not enforced by the type itself --
       *     call [`LoopConfig::validate`] on a `LoopConfig` built from external input (CLI flags,
       *     an imported template) before using it, to catch an out-of-range value before it
       *     reaches a live loop.
       */
      relay_amp_percent: number;
    };
    /**
     * @description A snapshot of the engine's observable state after a `step()` call — the fields a
     *     golden-master trace comparison checks against the legacy CSV log's per-tick columns
     *     (`Hysteresis`, `MvValueCurrent`, `MvSignNextStep`, `CounterAllSwitches`).
     */
    MrftState: {
      /** Format: int32 */
      counter_all_switches: number;
      /**
       * Format: int32
       * @description Whole relay cycles completed so far. Mirrors `GetCyclesCompleted`.
       */
      cycles_completed: number;
      /**
       * Format: int32
       * @description Whole relay cycles remaining. Mirrors `GetCyclesRemaining`; reaches `0` on the tick of
       *     the final switch, which is what triggers the snap-back to `mv_ini` instead of a full
       *     relay step.
       */
      cycles_remaining: number;
      /** Format: float */
      hysteresis: number;
      /** Format: int32 */
      mv_sign_next_step: number;
      /** Format: float */
      mv_value_current: number;
    };
    /**
     * @description A process/loop category. Each has its own row in the tuning-constant matrices in
     *     [`crate::constants`] and its own default cycle/noise-protection settings.
     *
     *     Discriminants double as the row index into those matrices — see
     *     [`ProcessType::index`].
     * @enum {string}
     */
    ProcessType:
      | "flow"
      | "pressure_line"
      | "pressure_vessel"
      | "level"
      | "temperature_mixing"
      | "temperature_heat_exchange";
    /**
     * @description How a DCS expresses the proportional term.
     * @enum {string}
     */
    ProportionalType: "gain" | "band";
    /**
     * @description How aggressively a tuning result should push the loop: a faster response trades off
     *     stability margin, a more sluggish response trades off speed.
     * @enum {string}
     */
    ResponseLevel: "aggressive" | "moderate" | "sluggish";
    /**
     * @description The outcome of a best-effort loop-restore attempt made after a run ended --
     *     `safety-restore-guard` (finding 3 of the live-plant safety review). Recorded via
     *     [`TuneRunRow::record_restore_status`]; `NULL` in the database (mapped to `None` on
     *     [`TuneRunRow::restore_status`]) means no restore was ever attempted -- either the run
     *     never mutated the loop at all, or it hasn't ended yet.
     * @enum {string}
     */
    RestoreStatus: "confirmed" | "incomplete";
    /** @description Local projection of [`TuneResultRow`]. */
    ResultResponse: {
      /** Format: float */
      derivative: number;
      /** Format: float */
      integral: number;
      /** Format: float */
      kp: number;
      /** Format: float */
      proportional: number;
      response_level: components["schemas"]["ResponseLevel"];
      /** Format: float */
      td_minutes: number;
      /** Format: float */
      ti_minutes: number;
    };
    /**
     * @description Whether a best-effort rollback of a partially-completed PID write was attempted and, if
     *     so, whether it succeeded. See [`TuneWriteRow::rollback_state`] for when this is `None`.
     * @enum {string}
     */
    RollbackState: "succeeded" | "failed";
    RunDetailResponse: {
      backend: components["schemas"]["TuneBackend"];
      /** Format: date-time */
      completed_at?: string | null;
      config: components["schemas"]["LoopConfig"];
      failure_reason?: string | null;
      /** Format: int64 */
      id: number;
      initial_readings?:
        null | components["schemas"]["InitialReadingsResponse"];
      loop_name: string;
      outcome: components["schemas"]["TuneOutcome"];
      restore_detail?: string | null;
      restore_status?: null | components["schemas"]["RestoreStatus"];
      results: components["schemas"]["ResultResponse"][];
      samples: components["schemas"]["SampleResponse"][];
      /** Format: date-time */
      started_at: string;
      /**
       * @description Name of the template snapshotted onto this run at start time -- not necessarily what
       *     `template_name` currently resolves to in the catalog (`safety-run-snapshot`).
       */
      template_name: string;
      template_origin: components["schemas"]["TemplateOrigin"];
      writes: components["schemas"]["WriteResponse"][];
    };
    RunListResponse: {
      /**
       * @description How many rows are in `runs` (this page) -- distinct from `total`, the count of every
       *     run matching the filter across all pages.
       */
      returned: number;
      runs: components["schemas"]["RunSummaryResponse"][];
      /** Format: int64 */
      total: number;
    };
    /**
     * @description One run in `GET /api/runs`'s `runs` array -- deliberately a subset matching the CLI's own
     *     `history list` table columns, not the full detail (that's [`RunDetailResponse`], for
     *     `GET /api/runs/{id}`).
     */
    RunSummaryResponse: {
      backend: components["schemas"]["TuneBackend"];
      /** Format: int64 */
      id: number;
      loop_name: string;
      outcome: components["schemas"]["TuneOutcome"];
      process_type: components["schemas"]["ProcessType"];
      /** Format: date-time */
      started_at: string;
    };
    /**
     * @description How much a [`TuneSampleRow`]'s `sample.pv` reading should be trusted, as recorded at the
     *     moment it was read (finding 5 of the live-plant safety review).
     *
     *     A `bhtune-db`-local mirror of [`bhtune_backend::Quality`], not a reuse of it directly:
     *     `bhtune-db` deliberately doesn't depend on `bhtune-backend` (a leaf I/O-adapter crate with
     *     a much heavier dependency tree -- `tokio`, `tonic`, `opcda-bridge` -- that has no business
     *     in the persistence crate just to name one three-variant enum), so `bhtune-cli`, which
     *     already depends on both, is the one place that converts between them. This mirrors
     *     [`TemplateOrigin`]'s own precedent: a small, persistence-local enum rather than a second
     *     dependency edge.
     * @enum {string}
     */
    SampleQuality: "good" | "uncertain" | "bad";
    /**
     * @description One recorded tick: the [`Tick`] input and resulting engine state, plus the backend-
     *     reported PV quality at read time. `Tick`/`MrftState` already derive `Serialize` in
     *     `bhtune-core` (they round-trip through golden-trace fixtures too), so they're embedded
     *     directly rather than re-projected field-by-field like the other DTOs here.
     */
    SampleResponse: {
      pv_quality: components["schemas"]["SampleQuality"];
      sample: components["schemas"]["Tick"];
      state: components["schemas"]["MrftState"];
      /** Format: int64 */
      tick_index: number;
    };
    /**
     * @description The body of `POST /api/runs` -- full field parity with [`TuneArgs`], since starting a run
     *     over HTTP must be able to express everything `bhtune tune` can. Every field that has a
     *     CLI default (`--sim-gain`, `--poll-interval-ms`, etc.) repeats that exact default here via
     *     `#[serde(default = "...")]`, so an HTTP caller that omits a field gets identical behavior
     *     to a CLI invocation that omits the matching flag. `Option<T>` fields need no
     *     `#[serde(default)]` of their own -- serde already treats a missing key as `None` for an
     *     `Option` field.
     */
    StartRunRequest: {
      /**
       * @description Accept `Quality::Uncertain` OPC readings instead of hard-failing on them. See
       *     [`TuneArgs::allow_uncertain_quality`].
       */
      allow_uncertain_quality?: boolean;
      /**
       * @description Which backend drives this tune. `"replay"` is rejected -- that backend exists only
       *     for offline golden-trace validation, not for starting a live/simulated run.
       */
      backend: components["schemas"]["TuneBackend"];
      /**
       * @description opcda-bridge gateway address. Only meaningful with `backend: "opcda"` (default:
       *     resolved the same way the CLI resolves `--bridge-host`, via this process's own
       *     config/env).
       */
      bridge_host?: string | null;
      controller_type: components["schemas"]["ControllerType"];
      /**
       * Format: int32
       * @description Relay cycles to count once the skip period ends (default: looked up per
       *     `process_type`).
       */
      cycles_count?: number | null;
      /**
       * Format: int32
       * @description Relay cycles to skip before counting begins (default: looked up per `process_type`).
       */
      cycles_skip?: number | null;
      direction?: null | components["schemas"]["ControllerDirection"];
      /**
       * Format: int32
       * @description Pre/post-test recording padding, in seconds.
       */
      mrft_delay?: number;
      /**
       * Format: float
       * @description Fixed MV range high, overriding a live tag read.
       */
      mv_range_high?: number | null;
      /**
       * Format: float
       * @description Fixed MV range low, overriding a live tag read.
       */
      mv_range_low?: number | null;
      /** @description A friendly name for this run, recorded as `loop_name` (default: the PV tag name). */
      name?: string | null;
      /**
       * Format: int32
       * @description Seconds a switch must persist before it's accepted (default: looked up per
       *     `process_type`).
       */
      noise_protection_secs?: number | null;
      /**
       * Format: int64
       * @description Cap on any single backend read/write during the run, in seconds.
       */
      op_timeout_secs?: number;
      /**
       * Format: int64
       * @description How often to poll the backend, in milliseconds.
       */
      poll_interval_ms?: number;
      process_type: components["schemas"]["ProcessType"];
      /**
       * Format: float
       * @description Fixed PV range high, overriding a live tag read. Required for `backend: "simulator"`,
       *     which has no range tags at all.
       */
      pv_range_high?: number | null;
      /**
       * Format: float
       * @description Fixed PV range low, overriding a live tag read.
       */
      pv_range_low?: number | null;
      /**
       * Format: float
       * @description Relay amplitude, as a percentage of the MV range.
       */
      relay_amp: number;
      /**
       * Format: int64
       * @description Cap on restoring the loop to its pre-test state after the run ends, in seconds.
       */
      restore_timeout_secs?: number;
      /** @description OPC DA server ProgID. Required with `backend: "opcda"`. */
      server?: string | null;
      /**
       * Format: float
       * @description Simulator dead time, in seconds (`backend: "simulator"` only).
       */
      sim_dead_time?: number;
      /**
       * Format: float
       * @description Simulator process gain (`backend: "simulator"` only).
       */
      sim_gain?: number;
      /**
       * Format: float
       * @description Simulator initial MV (`backend: "simulator"` only).
       */
      sim_initial_mv?: number;
      /**
       * Format: float
       * @description Simulator initial PV (`backend: "simulator"` only).
       */
      sim_initial_pv?: number;
      /**
       * Format: float
       * @description Simulator measurement noise amplitude (`backend: "simulator"` only).
       */
      sim_noise?: number;
      /**
       * Format: int64
       * @description Simulator RNG seed, for reproducible noise (`backend: "simulator"` only).
       */
      sim_seed?: number;
      /**
       * Format: float
       * @description Simulator process time constant, in seconds (`backend: "simulator"` only).
       */
      sim_tau?: number;
      /** @description PV tag prefix; ignored for `backend: "simulator"`. See [`TuneArgs::tagname`]. */
      tagname: string;
      /** @description DCS/PLC template name (see `GET /api/templates`). */
      template: string;
      /**
       * Format: int64
       * @description Hard wall-clock cap on this run's total duration, in seconds. See
       *     [`TuneArgs::timeout_secs`] -- always enforced, exactly as for a CLI-driven run.
       */
      timeout_secs?: number;
      write_pid?: null | components["schemas"]["ResponseLevel"];
      /**
       * @description Confirm an unattended PID write-back. Required alongside `write_pid` -- the request
       *     is rejected otherwise, identically to `--write-pid` without `--yes` on the CLI.
       */
      yes?: boolean;
    };
    /**
     * @description Where a `dcs_templates` row came from, and -- since [`TuneRunRow`] snapshots a copy of one
     *     at [`TuneRunRow::start`] time -- where a run's snapshotted template came from too. Kept as
     *     one definition reused by both tables (`dcs_templates.origin`, `tune_runs.template_origin`)
     *     rather than two, so they can never drift on what the possible origins even are, and so a
     *     run's history never needs to look the original row back up to know its provenance --
     *     which matters precisely because that row might no longer exist, or might have been
     *     re-imported under a different origin since.
     *
     *     `builtin` and `catalog` rows are re-upserted from their respective data files on every
     *     startup ([`crate::seed::seed_templates`]); `user` rows (hand-imported via `bhtune template
     *     import`, or created through a future GUI editor) are never auto-touched -- auto-reseeding
     *     a hand-edited row would silently discard someone's own customization, while *not*
     *     reseeding a shipped preset would mean a suffix/unit fix in a later release never reaches
     *     existing installs.
     * @enum {string}
     */
    TemplateOrigin: "builtin" | "catalog" | "user";
    /**
     * @description The HTTP-facing shape of a stored template: the caller-supplied [`DcsTemplate`] fields
     *     flattened alongside the database-assigned `id`/`origin`/timestamps. Per this workspace's
     *     established DTO-decoupling convention (see `bhtune-cli`'s `commands::history` module doc
     *     comments), [`DcsTemplateRow`] itself deliberately does not derive `Serialize` -- every
     *     JSON-facing consumer builds its own projection rather than the DB row shape leaking
     *     straight onto the wire.
     */
    TemplateResponse: components["schemas"]["DcsTemplate"] & {
      /** Format: date-time */
      created_at: string;
      /** Format: int64 */
      id: number;
      origin: components["schemas"]["TemplateOrigin"];
      /** Format: date-time */
      updated_at: string;
    };
    /**
     * @description One PV sample fed into the engine. The engine has no clock of its own — every timestamp
     *     it ever reasons about arrives through a `Tick`.
     */
    Tick: {
      /** Format: float */
      pv: number;
      /** Format: date-time */
      time: string;
    };
    /**
     * @description The time unit a DCS expects for integral/derivative parameters.
     * @enum {string}
     */
    TimeUnit: "seconds" | "minutes";
    /**
     * @description Which [`crate`]-agnostic I/O backend a run used. Lives in `bhtune-db` rather than
     *     `bhtune-core` because it's a persistence/orchestration concept (which adapter drove this
     *     run), not a domain concept the pure MRFT engine itself needs to know about.
     * @enum {string}
     */
    TuneBackend: "opcda" | "simulator" | "replay";
    /**
     * @description A run's lifecycle state.
     * @enum {string}
     */
    TuneOutcome: "running" | "completed" | "failed" | "aborted";
    /**
     * @description Distinguishes a normal write-back from `bhtune history revert` undoing an earlier one.
     *     Both share [`TuneWriteRow`]'s exact shape -- pre-read, write-and-verify each constant,
     *     audit the outcome -- so they live in the same table rather than a second near-duplicate
     *     one; `kind` is the one column that tells them apart.
     * @enum {string}
     */
    WriteKind: "write" | "revert";
    /** @description Local projection of [`TuneWriteRow`]. */
    WriteResponse: {
      /** Format: float */
      derivative_previous?: number | null;
      /** Format: float */
      derivative_readback?: number | null;
      /** Format: float */
      derivative_written?: number | null;
      error_message?: string | null;
      /** Format: float */
      integral_previous?: number | null;
      /** Format: float */
      integral_readback?: number | null;
      /** Format: float */
      integral_written?: number | null;
      kind: components["schemas"]["WriteKind"];
      /** Format: float */
      proportional_previous?: number | null;
      /** Format: float */
      proportional_readback?: number | null;
      /** Format: float */
      proportional_written?: number | null;
      response_level: components["schemas"]["ResponseLevel"];
      rollback_error?: string | null;
      rollback_state?: null | components["schemas"]["RollbackState"];
      success: boolean;
      /** Format: date-time */
      written_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The process is up and answering HTTP. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  list_runs: {
    parameters: {
      query?: {
        loop_id?: number;
        process_type?: components["schemas"]["ProcessType"];
        controller_type?: components["schemas"]["ControllerType"];
        outcome?: components["schemas"]["TuneOutcome"];
        backend?: components["schemas"]["TuneBackend"];
        started_after?: string;
        started_before?: string;
        template_name?: string;
        template_origin?: components["schemas"]["TemplateOrigin"];
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of runs matching the filter. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunListResponse"];
        };
      };
    };
  };
  start_run: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartRunRequest"];
      };
    };
    responses: {
      /** @description The run was started; detail reflects its state right now. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetailResponse"];
        };
      };
      /** @description The request failed validation, or `prepare()` itself failed (unknown template, invalid flag combination, unreachable backend). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Another tune run is already active. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  show_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The full recorded detail for one run. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetailResponse"];
        };
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  cancel_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation requested (or the run was already inactive). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  list_templates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Every stored template, ordered by name. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateResponse"][];
        };
      };
    };
  };
  create_template: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DcsTemplate"];
      };
    };
    responses: {
      /** @description Template created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateResponse"];
        };
      };
      /** @description The template failed validation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description A template with this name already exists. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateResponse"];
        };
      };
      /** @description No template with that name. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  delete_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Template deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No template with that name. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The template is still referenced by one or more saved loops. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
}
