/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_config"];
    put: operations["put_config"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe. */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/opc/browse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the tags/branches directly under one tree level of an OPC DA server.
     * @description `GET /api/opc/browse` -- one level at a time (not a recursive dump of the whole tree),
     *     matching `Driver::browse`'s own contract; the GUI's tag-tree modal calls this again for
     *     each branch the user expands. Requires `opc_server` (from the query or config) since,
     *     unlike `GET /api/opc/servers`, browsing needs a specific server to connect to.
     */
    get: operations["browse"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/opc/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read one tag's current value, quality, and timestamp.
     * @description `GET /api/opc/read` -- backs the GUI's "Test connection" button (read the tag the user is
     *     about to use as the loop's PV and show what comes back) and the tag-tree's live preview.
     *     Deliberately does not enforce [`bhtune_driver::Quality::is_trustworthy`] the way a real
     *     tune's readings must -- this is a diagnostic command, so it reports whatever quality it
     *     gets rather than failing on `Uncertain`/`Bad`, matching `bhtune opc read`'s own behavior.
     */
    get: operations["read"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/opc/servers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List every OPC DA server registered on the bridge gateway's own host.
     * @description `GET /api/opc/servers` -- powers the GUI's server dropdown. Server discovery needs only a
     *     bridge host, not a ProgID, so it cannot be a `Driver` trait method (constructing a
     *     `Driver` already requires the ProgID this call exists to find); it's the free function
     *     `bhtune_driver::list_opcda_servers` instead. An empty `servers` array is a normal, valid
     *     answer, not an error -- only a connection failure or timeout is a 400.
     */
    get: operations["servers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List tune runs, filtered and paginated.
     * @description `GET /api/runs` -- newest-started-first, filtered by every present [`RunListQuery`] field,
     *     one [`Pagination`] page at a time.
     */
    get: operations["list_runs"];
    put?: never;
    /**
     * Start a new tune run.
     * @description `POST /api/runs` -- runs `prepare()` (template lookup, tag derivation, driver connect,
     *     and the `tune_runs` insert) inline and returns as soon as that succeeds, having already
     *     `tokio::spawn`ed the actual polling/tuning phase in the background. `201 Created` carries
     *     the same [`RunDetailResponse`] `GET /api/runs/{id}` would show for this run at this
     *     instant (almost certainly still `outcome: "running"`) -- poll that endpoint, or use
     *     `POST /api/runs/{id}/cancel`, to follow the run to completion.
     *
     *     `409 Conflict` if an exclusive post-hoc PID write/revert is active; independent tune runs
     *     may execute concurrently.
     */
    post: operations["start_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the saved New Tune draft, or `null` when no draft has been saved yet. */
    get: operations["get_draft"];
    /** Replaces the saved New Tune draft and returns the stored value. */
    put: operations["put_draft"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/last-request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The most recently started run's original request, if any.
     * @description `GET /api/runs/last-request` -- returns the newest run's `request_json`
     *     (`db-run-request-snapshot`), parsed back into a [`StartRunRequest`], or `null` on a fresh
     *     install with no runs yet, or if the newest run's stored request isn't usable (see
     *     [`parse_stored_request`]) (`ui-prefill-last-run`). The New tune form uses this only as a
     *     one-time fallback when no mutable `/api/runs/draft` exists, which lets older installations
     *     upgrade without losing their previous run settings while keeping future edits independent of
     *     immutable history. "Newest" means newest by `started_at`, matching `GET /api/runs`'s own
     *     ordering, regardless of that run's `outcome`.
     */
    get: operations["last_request"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch one run's full detail.
     * @description `GET /api/runs/{id}` -- 404 if no run has that id.
     */
    get: operations["show_run"];
    put?: never;
    post?: never;
    /**
     * Delete one run and its recorded samples/results/write-back audit rows.
     * @description `DELETE /api/runs/{id}` -- 404 if no run has that id, 409 if the run's own recorded
     *     `outcome` is still [`TuneOutcome::Running`] (deleting the row out from under an in-flight
     *     task would corrupt whatever it tries to write next; cancel it first). Deliberately checks
     *     the run row's own `outcome` rather than [`crate::active_run::ActiveRun`]'s in-memory
     *     active-run registry entry: `drive()` persists every terminal outcome (`persist_results` then
     *     `TuneRunRow::complete`/`fail`/`abort`) *before* returning, and `ActiveRun::release` only
     *     runs strictly after `drive()` returns (see `routes::runs::start_run`'s spawned task), so
     *     there is a real -- if brief -- window where a run's outcome is already durably
     *     `completed`/`failed`/`aborted` but `ActiveRun` hasn't been told the registry entry is free yet.
     *     Checking the DB's own authoritative, durable state instead of the best-effort in-memory
     *     tracker closes that race outright, rather than requiring the caller to retry (as
     *     `frontend/e2e/tune.spec.ts`'s `startTune()` already has to for the equivalent gap on the
     *     *start* side).
     */
    delete: operations["delete_run"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request cancellation of a run, exactly as if Ctrl+C had been pressed against an
     *     equivalent CLI-driven run.
     * @description `POST /api/runs/{id}/cancel` -- `404` if no run has that id; otherwise always `204`,
     *     whether or not the run was actually active at the moment this was called (a run that
     *     already finished simply has nothing left to cancel). Cancellation is asynchronous: the
     *     run's background task still has to observe it, stop polling, and run its restore --
     *     `GET /api/runs/{id}` shows the eventual outcome.
     */
    post: operations["cancel_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export one run's recorded samples as CSV or JSON.
     * @description `GET /api/runs/{id}/export?format=csv|json` -- 404 if no run has that id or it has no
     *     recorded samples yet. Defaults to CSV. Sets `Content-Disposition: attachment` so a
     *     browser downloads the response as a file rather than rendering it.
     */
    get: operations["export_run"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}/notes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Replace the operator notes attached to a run.
     * @description `PUT /api/runs/{id}/notes` deliberately works for both running and terminal runs. Notes
     *     are metadata, not a plant mutation, so they do not take the active-run registry reservation.
     */
    put: operations["update_notes"];
    post?: never;
    /**
     * Clear a run's operator notes.
     * @description `DELETE /api/runs/{id}/notes` is idempotent and works while a run is active or after it
     *     finishes.
     */
    delete: operations["delete_notes"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}/revert": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revert a run's most recent PID write-back, restoring the pre-write values it recorded.
     * @description `POST /api/runs/{id}/revert` -- no request body: like `POST /api/runs/{id}/cancel`, the
     *     GUI's own confirmation dialog (naming the tag, the tags, and the exact values from
     *     `writes[]`) is the human confirmation step, not a body field. Finds the run's last
     *     [`WriteKind::Write`] row regardless of whether it succeeded (matching
     *     `bhtune history revert`'s own semantics exactly), requiring it to have recorded pre-write
     *     values to revert to. A revert never attempts a nested rollback of itself if it fails
     *     partway through -- see [`WriteKind`]'s doc comment.
     *
     *     Always `200` once the request itself is valid and no conflicting operation is active; see
     *     [`reserve_connect_and_write`]'s doc comment for why a physical revert failure is not a
     *     `4xx`/`5xx`.
     */
    post: operations["revert_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream per-tick engine state for one run over Server-Sent Events.
     * @description `GET /api/runs/{id}/stream` -- 404 if no run has that id. Emits one `initial` event (JSON
     *     body: [`InitialReadingsResponse`]) as soon as the driver's initial snapshot is persisted,
     *     then a `sample` event (JSON body: [`SampleResponse`], the same shape
     *     `GET /api/runs/{id}`'s `samples` array already uses) for every tick recorded so far and
     *     every new tick recorded while connected, followed by exactly one final `done` event (JSON
     *     body: [`RunStreamDone`]) once the run reaches a terminal outcome -- after which the
     *     connection closes. Safe to open at any point in a run's lifecycle, including after it has
     *     already finished: the initial snapshot (when available) and every sample are replayed once,
     *     immediately followed by `done`.
     */
    get: operations["stream_run"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{id}/write": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Write one of a run's calculated candidate PID parameter sets back to the live loop.
     * @description `POST /api/runs/{id}/write` -- unlike the CLI's `--write-pid`, which can only fire once
     *     at the end of the run it belongs to, this can be called at any time after the run has
     *     finished, letting an engineer compare Sluggish/Moderate/Aggressive on screen before
     *     picking one. Pre-reads the selected tag's current P/I/D, writes and verifies each constant in
     *     turn, and rolls back to the pre-read values if a later constant is rejected
     *     (`safety-writeback-rollback`) -- recorded as a new write-back audit row exactly like an
     *     in-run write.
     *
     *     Always `200` once the request itself is valid and no conflicting operation is active,
     *     whether or not the write actually succeeded -- see [`reserve_connect_and_write`]'s doc
     *     comment for why a physical write failure is not a `4xx`/`5xx`.
     */
    post: operations["write_run"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List every stored template.
     * @description `GET /api/templates` -- every stored template (built-in, catalog, and user-created
     *     alike), ordered by name, for a template picker.
     */
    get: operations["list_templates"];
    put?: never;
    /**
     * Create a new, user-owned template.
     * @description `POST /api/templates` -- 400 if [`DcsTemplate::validate`] rejects the body, 409 if a
     *     template with the same name already exists.
     */
    post: operations["create_template"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/templates/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch one template by name.
     * @description `GET /api/templates/{name}` -- 404 if no template has that name.
     */
    get: operations["get_template"];
    /**
     * Update an existing, user-owned template.
     * @description `PUT /api/templates/{name}` -- 404 if no template has that name, 400 if the body fails
     *     [`DcsTemplate::validate`] or its `name` doesn't match the path (renaming isn't supported
     *     here -- delete and recreate instead, the same restriction
     *     [`bhtune_db::models::DcsTemplateRow::update`] itself has), 409 if the template's origin
     *     isn't [`TemplateOrigin::User`]: `builtin`/`catalog` rows are re-upserted from their
     *     source file on every startup (see `bhtune_db::seed`), so an HTTP edit to one would just
     *     be silently discarded on the next restart -- the same reasoning that keeps `bhtune
     *     template import` from touching them either.
     */
    put: operations["update_template"];
    post?: never;
    /**
     * Delete a template by name.
     * @description `DELETE /api/templates/{name}` -- 404 if no template has that name, 409 if it is still
     *     referenced by a saved loop (`bhtune_db::DbError::TemplateInUse`, mapped by
     *     `From<DbError> for ApiError`).
     */
    delete: operations["delete_template"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ConfigResponse: {
      backup_path?: string | null;
      config_path: string;
      effective: components["schemas"]["ConfigValues"];
      revision: string;
      source: components["schemas"]["ConfigSources"];
      toml: components["schemas"]["ConfigTomlValues"];
    };
    ConfigSources: {
      allow_uncertain_quality: string;
      retention_days: string;
      tuning: components["schemas"]["ConfigTuningSources"];
    };
    ConfigTomlValues: {
      allow_uncertain_quality?: boolean | null;
      /** Format: int32 */
      retention_days?: number | null;
      tuning: components["schemas"]["ConfigTuningTomlValues"];
    };
    ConfigTuningSources: {
      mrft_delay_secs: string;
      op_timeout_secs: string;
      poll_interval_ms: string;
      restore_timeout_secs: string;
      timeout_secs: string;
    };
    ConfigTuningTomlValues: {
      /** Format: int32 */
      mrft_delay_secs?: number | null;
      /** Format: int64 */
      op_timeout_secs?: number | null;
      /** Format: int64 */
      poll_interval_ms?: number | null;
      /** Format: int64 */
      restore_timeout_secs?: number | null;
      /** Format: int64 */
      timeout_secs?: number | null;
    };
    ConfigTuningValues: {
      /** Format: int32 */
      mrft_delay_secs: number;
      /** Format: int64 */
      op_timeout_secs: number;
      /** Format: int64 */
      poll_interval_ms: number;
      /** Format: int64 */
      restore_timeout_secs: number;
      /** Format: int64 */
      timeout_secs: number;
    };
    ConfigValues: {
      allow_uncertain_quality: boolean;
      /** Format: int32 */
      retention_days?: number | null;
      tuning: components["schemas"]["ConfigTuningValues"];
    };
    /**
     * @description Direct-acting (increasing MV increases PV) or Reverse-acting (increasing MV decreases
     *     PV).
     * @enum {string}
     */
    ControllerDirection: "direct" | "reverse";
    /**
     * @description A PID controller structure. Discriminants double as the column index into the
     *     tuning-constant matrices in [`crate::constants`].
     * @enum {string}
     */
    ControllerType: "p" | "pi" | "pid";
    /** @description One DCS/PLC vendor's conventions. */
    DcsTemplate: {
      /**
       * @description The raw value a Controller Direction tag holds when the controller is Direct
       *     acting; see [`crate::direction::ControllerDirection::from_raw_tag_value`].
       */
      controller_action_direct_value: string;
      controller_direction_suffix: string;
      controller_mode_suffix: string;
      derivative_constant_suffix: string;
      derivative_type: components["schemas"]["DerivativeType"];
      derivative_unit: components["schemas"]["TimeUnit"];
      /** @description Free-text description of the control system this template targets. */
      description?: string | null;
      integral_constant_suffix: string;
      integral_type: components["schemas"]["IntegralType"];
      integral_unit: components["schemas"]["TimeUnit"];
      lower_mv_range_suffix: string;
      lower_pv_range_suffix: string;
      manipulated_variable_suffix: string;
      /**
       * @description The raw value a Mode Attribute tag holds when in "Program" mode (permits external
       *     OPC writes). `None` when the DCS has no mode-attribute concept.
       */
      mode_attribute_program_value?: string | null;
      mode_attribute_suffix: string;
      mode_auto_value: string;
      /** @description The DCS-specific raw values a Mode tag holds for Manual/Auto. */
      mode_manual_value: string;
      name: string;
      /**
       * @description OPC item-name suffixes, combined with a PV tag's path prefix by
       *     [`crate::tags::derive_tag`] to fill in the rest of the tag set. An empty suffix
       *     means the corresponding tag is not applicable for this DCS (e.g. some DCS families
       *     have no mode-attribute concept).
       */
      process_variable_suffix: string;
      proportional_constant_suffix: string;
      proportional_type: components["schemas"]["ProportionalType"];
      /**
       * @description If true, the controller mode is switched back to its original mode (e.g.
       *     Auto/Cascade) after a completed MRFT test. Has no effect if the loop was already in
       *     Manual at test start.
       */
      revert_mode: boolean;
      setpoint_variable_suffix: string;
      /**
       * @description Citation for where this mapping came from (a manual, a field deployment).
       *     Provenance, not a correctness guarantee -- there is deliberately no separate
       *     "verified" trust field; everything accepted into the catalog is treated as verified,
       *     and real mapping errors are fixed as bugs when they surface.
       */
      source?: string | null;
      upper_mv_range_suffix: string;
      upper_pv_range_suffix: string;
      /**
       * @description DCS/PLC releases this mapping is known to apply to (e.g. `["R5", "R6"]`), in each
       *     vendor's own version-naming convention rather than a normalized scheme. A newer
       *     release that changes tag conventions gets its *own* template entry with its own
       *     `name` and `versions` list -- never an edit to this one in place, since sites still
       *     running the older release depend on the existing mapping (see
       *     `docs/dcs-templates.md`). May be empty for a contribution whose version coverage
       *     isn't yet known; `name` is what makes a template unique, not `versions`.
       */
      versions?: string[];
    };
    /**
     * @description How a DCS expresses the derivative term.
     * @enum {string}
     */
    DerivativeType: "derivative_time" | "derivative_gain";
    /**
     * @description The source selector state used only by the mutable New Tune draft.
     * @enum {string}
     */
    DraftTagSource: "template" | "custom";
    /** @description Per-tag source choices in the New Tune mapping editor. */
    DraftTagSources: {
      controller_mode: components["schemas"]["DraftTagSource"];
      derivative_constant: components["schemas"]["DraftTagSource"];
      integral_constant: components["schemas"]["DraftTagSource"];
      manipulated_variable: components["schemas"]["DraftTagSource"];
      mode_attribute: components["schemas"]["DraftTagSource"];
      process_variable: components["schemas"]["DraftTagSource"];
      proportional_constant: components["schemas"]["DraftTagSource"];
      setpoint_variable: components["schemas"]["DraftTagSource"];
    };
    /**
     * @description The source selector state used only by the mutable New Tune draft.
     * @enum {string}
     */
    DraftValueSource: "tag" | "custom" | "fixed";
    /** @description Per-direction/range source choices in the New Tune mapping editor. */
    DraftValueSources: {
      direction: components["schemas"]["DraftValueSource"];
      mv_range_high: components["schemas"]["DraftValueSource"];
      mv_range_low: components["schemas"]["DraftValueSource"];
      pv_range_high: components["schemas"]["DraftValueSource"];
      pv_range_low: components["schemas"]["DraftValueSource"];
    };
    /**
     * @description Concrete tune timing values after configuration defaults have been resolved.
     *
     *     Stored as one compact snapshot because these values are consumed together and have no
     *     SQL-level filtering requirement. `None` on [`TuneRunRow::effective_tuning`] identifies
     *     runs created before this snapshot existed or callers that have not recorded it yet.
     */
    EffectiveTuning: {
      /** Format: int32 */
      mrft_delay_secs: number;
      /** Format: int64 */
      op_timeout_secs: number;
      /** Format: int64 */
      poll_interval_ms: number;
      /** Format: int64 */
      restore_timeout_secs: number;
      /** Format: int64 */
      timeout_secs: number;
    };
    /**
     * @description The JSON body of every non-2xx response: `{"error": "<message>"}`. `pub`/`ToSchema` so
     *     every fallible `#[utoipa::path]` response can reference it (`body = ErrorBody`) and the
     *     generated OpenAPI spec -- and therefore the generated frontend TS client -- accurately
     *     types error bodies instead of `content?: never`.
     */
    ErrorBody: {
      error: string;
    };
    Health: {
      status: string;
      version: string;
    };
    /**
     * @description Local projection of [`bhtune_db::models::TuneRunInitialReadings`] -- see this module's
     *     doc comment for why every JSON-facing type here is its own projection rather than a
     *     `Serialize` impl on the `bhtune-db` row type.
     */
    InitialReadingsResponse: {
      controller_direction: components["schemas"]["ControllerDirection"];
      mode_attribute_raw?: string | null;
      mode_raw?: string | null;
      /** Format: float */
      mv_ini: number;
      /** Format: float */
      mv_range_high: number;
      /** Format: float */
      mv_range_low: number;
      /** Format: float */
      pv_ini: number;
      /** Format: float */
      pv_range_high: number;
      /** Format: float */
      pv_range_low: number;
      /** Format: float */
      setpoint_ini?: number | null;
    };
    /**
     * @description How a DCS expresses the integral term.
     * @enum {string}
     */
    IntegralType: "reset_time" | "reset_rate" | "reset_gain";
    LoopConfig: {
      controller_type: components["schemas"]["ControllerType"];
      /**
       * Format: int32
       * @description Pre/post-test recording padding, in seconds. PV is still read and recorded during
       *     this period; no switch evaluation happens.
       */
      mrft_delay_secs: number;
      /** Format: int32 */
      noise_protection_secs: number;
      /** Format: int32 */
      num_cycles_count: number;
      /** Format: int32 */
      num_cycles_skip: number;
      process_type: components["schemas"]["ProcessType"];
      /**
       * Format: float
       * @description Relay amplitude as a percentage of the MV range. Not enforced by the type itself --
       *     call [`LoopConfig::validate`] on a `LoopConfig` built from external input (CLI flags,
       *     an imported template) before using it, to catch an out-of-range value before it
       *     reaches a live loop.
       */
      relay_amp_percent: number;
    };
    /**
     * @description A snapshot of the engine's observable state after a `step()` call — the fields a
     *     golden-master trace comparison checks against the legacy CSV log's per-tick columns
     *     (`Hysteresis`, `MvValueCurrent`, `MvSignNextStep`, `CounterAllSwitches`).
     */
    MrftState: {
      /** Format: int32 */
      counter_all_switches: number;
      /**
       * Format: int32
       * @description Whole relay cycles completed so far. Mirrors `GetCyclesCompleted`.
       */
      cycles_completed: number;
      /**
       * Format: int32
       * @description Whole relay cycles remaining. Mirrors `GetCyclesRemaining`; reaches `0` on the tick of
       *     the final switch, which is what triggers the snap-back to `mv_ini` instead of a full
       *     relay step.
       */
      cycles_remaining: number;
      /** Format: float */
      hysteresis: number;
      /** Format: int32 */
      mv_sign_next_step: number;
      /** Format: float */
      mv_value_current: number;
    };
    /**
     * @description The physical purpose of one accepted manipulated-variable command.
     * @enum {string}
     */
    MvActuationKind: "relay" | "restore";
    /**
     * @description Local projection of one accepted OPC DA manipulated-variable command and its independent
     *     live readback evidence. Commanded MV samples remain in [`SampleResponse`]; this audit trail
     *     is the only response surface that reports measured MV values.
     */
    MvActuationResponse: {
      /** Format: int64 */
      attempt_count: number;
      /** Format: date-time */
      commanded_at: string;
      /** Format: date-time */
      confirmation_due_at: string;
      detail?: string | null;
      /** Format: int64 */
      id: number;
      kind: components["schemas"]["MvActuationKind"];
      /** Format: date-time */
      last_checked_at?: string | null;
      /** Format: float */
      previous_commanded_mv?: number | null;
      /** Format: float */
      readback_mv?: number | null;
      readback_quality?: null | components["schemas"]["SampleQuality"];
      /** Format: int64 */
      sequence: number;
      status: components["schemas"]["MvActuationStatus"];
      /** Format: float */
      target_mv: number;
      /** Format: float */
      tolerance: number;
    };
    /**
     * @description Lifecycle state of one accepted manipulated-variable command.
     * @enum {string}
     */
    MvActuationStatus:
      "pending" | "confirmed" | "failed" | "unverified" | "superseded";
    /**
     * @description The editable state of the New Tune form.
     *
     *     Fields are optional because the form is allowed to be incomplete while it is being edited.
     *     The frontend sends the complete shape on each save, using `null` for a cleared numeric or
     *     enum field. Notes are intentionally absent: they describe one run, not a reusable draft.
     */
    NewRunDraft: {
      bridge_host?: string | null;
      controller_type?: null | components["schemas"]["ControllerType"];
      /** Format: int32 */
      cycles_count?: number | null;
      /** Format: int32 */
      cycles_skip?: number | null;
      direction?: null | components["schemas"]["ControllerDirection"];
      driver?: null | components["schemas"]["TuneDriver"];
      /** Format: int32 */
      mrft_delay?: number | null;
      /** Format: float */
      mv_range_high?: number | null;
      /** Format: float */
      mv_range_low?: number | null;
      /** Format: int32 */
      noise_protection_secs?: number | null;
      /** Format: int64 */
      op_timeout_secs?: number | null;
      /** Format: int64 */
      poll_interval_ms?: number | null;
      process_type?: null | components["schemas"]["ProcessType"];
      /** Format: float */
      pv_range_high?: number | null;
      /** Format: float */
      pv_range_low?: number | null;
      /** Format: float */
      relay_amp?: number | null;
      /** Format: int64 */
      restore_timeout_secs?: number | null;
      server?: string | null;
      /** Format: float */
      sim_dead_time?: number | null;
      /** Format: float */
      sim_gain?: number | null;
      /** Format: float */
      sim_initial_mv?: number | null;
      /** Format: float */
      sim_initial_pv?: number | null;
      /** Format: float */
      sim_noise?: number | null;
      /** Format: int64 */
      sim_seed?: number | null;
      /** Format: float */
      sim_tau?: number | null;
      source_direction?: null | components["schemas"]["ControllerDirection"];
      source_driver?: null | components["schemas"]["TuneDriver"];
      /** Format: float */
      source_mv_range_high?: number | null;
      /** Format: float */
      source_mv_range_low?: number | null;
      /** Format: float */
      source_pv_range_high?: number | null;
      /** Format: float */
      source_pv_range_low?: number | null;
      tag_overrides?: null | components["schemas"]["TagOverrides"];
      tag_sources?: null | components["schemas"]["DraftTagSources"];
      tagname?: string | null;
      template?: string | null;
      /** Format: int64 */
      timeout_secs?: number | null;
      value_sources?: null | components["schemas"]["DraftValueSources"];
      write_pid?: null | components["schemas"]["ResponseLevel"];
      yes?: boolean | null;
    };
    /** @description Response body of `GET /api/opc/browse`. */
    OpcBrowseResponse: {
      nodes: components["schemas"]["OpcTagNodeResponse"][];
    };
    /**
     * @description Response body of `GET /api/opc/read`.
     *
     *     `quality` reuses [`SampleQuality`] rather than a third quality representation --
     *     `bhtune-db`'s `SampleQuality` (mapped from the driver's live [`bhtune_driver::Quality`] by
     *     [`sample_quality_from_driver`]) is already exposed directly over HTTP in
     *     `GET /api/runs/{id}`'s `SampleResponse::pv_quality` (see `routes::history`), so this
     *     follows that same precedent instead of inventing a parallel `OpcQualityResponse` enum.
     */
    OpcReadResponse: {
      quality: components["schemas"]["SampleQuality"];
      tag: string;
      /**
       * Format: date-time
       * @description Always `null` for the OPC DA driver today: the gateway's last-change time is a
       *     *local*, offset-less string with no reliable way to convert it to a trustworthy
       *     `DateTime<Utc>` (see `bhtune_driver::opcda::tag_value_from_raw`'s doc comment) -- kept
       *     as a field rather than dropped entirely so a future driver that *can* supply a
       *     trustworthy instant (or a bridge protocol revision that reports the gateway's own
       *     timezone) doesn't need an API shape change to start populating it.
       */
      timestamp?: string | null;
      value: string;
    };
    /** @description Response body of `GET /api/opc/servers`. */
    OpcServersResponse: {
      servers: string[];
    };
    /**
     * @description One node of `GET /api/opc/browse`'s `nodes` array -- a plain HTTP-facing projection of
     *     [`bhtune_driver::TagNode`], per this workspace's DTO-decoupling convention (`bhtune-driver`
     *     types deliberately don't derive `Serialize`/`ToSchema`; every JSON-facing consumer builds
     *     its own projection instead).
     */
    OpcTagNodeResponse: {
      is_branch: boolean;
      tag: string;
    };
    /**
     * @description A run's snapshotted PID constant tag names, present only when all three were configured.
     *     Nested under `RunDetailResponse::pid_constant_tags` following the same
     *     "`Option<...>` presence itself is the signal" convention `initial_readings` already uses,
     *     rather than a separate boolean plus three more nullable top-level fields.
     */
    PidConstantTagsResponse: {
      derivative: string;
      integral: string;
      proportional: string;
    };
    /**
     * @description The operator-facing names for the three calculated PID constants, derived from the
     *     template snapshot stored on the run rather than the mutable template catalog.
     */
    PidParameterLabelsResponse: {
      derivative: string;
      integral: string;
      proportional: string;
    };
    /**
     * @description Operation-latency diagnostics captured while a run is polling.
     *
     *     Each category counts only operations that completed successfully. A zero count with
     *     `None` mean/max means that the operation did not occur during the run.
     */
    PollLatencyMetrics: {
      mv_verification: components["schemas"]["TimingSummary"];
      mv_write: components["schemas"]["TimingSummary"];
      pv_read: components["schemas"]["TimingSummary"];
      sample_persist: components["schemas"]["TimingSummary"];
      tick_work: components["schemas"]["TimingSummary"];
    };
    /**
     * @description A process/loop category. Each has its own row in the tuning-constant matrices in
     *     [`crate::constants`] and its own default cycle/noise-protection settings.
     *
     *     Discriminants double as the row index into those matrices — see
     *     [`ProcessType::index`].
     * @enum {string}
     */
    ProcessType:
      | "flow"
      | "pressure_line"
      | "pressure_vessel"
      | "level"
      | "temperature_mixing"
      | "temperature_heat_exchange";
    /**
     * @description How a DCS expresses the proportional term.
     * @enum {string}
     */
    ProportionalType: "gain" | "band";
    /**
     * @description How aggressively a tuning result should push the loop: a faster response trades off
     *     stability margin, a more sluggish response trades off speed.
     * @enum {string}
     */
    ResponseLevel: "aggressive" | "moderate" | "sluggish";
    /**
     * @description The outcome of a best-effort loop-restore attempt made after a run ended --
     *     `safety-restore-guard` (finding 3 of the live-plant safety review). Recorded via
     *     [`TuneRunRow::record_restore_status`]; `NULL` in the database (mapped to `None` on
     *     [`TuneRunRow::restore_status`]) means no restore was ever attempted -- either the run
     *     never mutated the loop at all, or it hasn't ended yet.
     * @enum {string}
     */
    RestoreStatus: "confirmed" | "incomplete";
    /** @description Local projection of [`TuneResultRow`]. */
    ResultResponse: {
      /** Format: float */
      derivative?: number | null;
      /** Format: float */
      integral?: number | null;
      invalid_reason?:
        null | components["schemas"]["TuningResultInvalidReason"];
      /** Format: float */
      kp?: number | null;
      /** Format: float */
      proportional?: number | null;
      response_level: components["schemas"]["ResponseLevel"];
      status: components["schemas"]["TuningResultStatus"];
      /** Format: float */
      td_minutes?: number | null;
      /** Format: float */
      ti_minutes?: number | null;
    };
    /**
     * @description Whether a best-effort rollback of a partially-completed PID write was attempted and, if
     *     so, whether it succeeded. See [`TuneWriteRow::rollback_state`] for when this is `None`.
     * @enum {string}
     */
    RollbackState: "succeeded" | "failed";
    RunDetailResponse: {
      /** @description Whether this run accepted `Uncertain` OPC quality, captured when the run started. */
      allow_uncertain_quality: boolean;
      /** @description The resolved bridge host this run actually used, matching `opc_server` above. */
      bridge_host?: string | null;
      /** Format: date-time */
      completed_at?: string | null;
      config: components["schemas"]["LoopConfig"];
      driver: components["schemas"]["TuneDriver"];
      effective_tuning?: null | components["schemas"]["EffectiveTuning"];
      failure_reason?: string | null;
      /** Format: int64 */
      id: number;
      initial_readings?:
        null | components["schemas"]["InitialReadingsResponse"];
      mv_actuations: components["schemas"]["MvActuationResponse"][];
      notes?: string | null;
      /**
       * @description The resolved OPC DA server ProgID this run actually used, or `None` for a
       *     simulator/replay run (`db-run-request-snapshot`). This is what `history revert`
       *     trusts over any `--server` flag -- see `bhtune-cli::commands::history`.
       */
      opc_server?: string | null;
      original_request?: null | components["schemas"]["StartRunRequest"];
      outcome: components["schemas"]["TuneOutcome"];
      pid_constant_tags?:
        null | components["schemas"]["PidConstantTagsResponse"];
      /**
       * @description Operator-facing calculated-result column labels from the run's historical template
       *     snapshot. Empty user-template suffixes use the conventional P/I/D labels.
       */
      pid_parameter_labels: components["schemas"]["PidParameterLabelsResponse"];
      restore_detail?: string | null;
      restore_status?: null | components["schemas"]["RestoreStatus"];
      results: components["schemas"]["ResultResponse"][];
      samples: components["schemas"]["SampleResponse"][];
      /** Format: date-time */
      started_at: string;
      tag_name: string;
      /**
       * @description Name of the template snapshotted onto this run at start time -- not necessarily what
       *     `template_name` currently resolves to in the catalog (`safety-run-snapshot`).
       */
      template_name: string;
      template_origin: components["schemas"]["TemplateOrigin"];
      timing_metrics?: null | components["schemas"]["TimingMetrics"];
      writes: components["schemas"]["WriteResponse"][];
    };
    /**
     * @description Format for `GET /api/runs/{id}/export` -- deliberately a local, HTTP-facing enum rather
     *     than reusing `bhtune_cli::args::ExportFormat` directly: that type is `clap`-oriented
     *     (`ValueEnum`) and has no `Deserialize`/`ToSchema`, matching this module's own
     *     DTO-decoupling convention (see the module doc comment). Converted to
     *     `bhtune_cli::args::ExportFormat` at the one call site that needs it ([`export_run`]), so
     *     the actual CSV/JSON serialization (`bhtune_cli::commands::export::samples_to_bytes`) is
     *     implemented exactly once and the CLI's `bhtune export` and this route can never disagree
     *     about what a run's export looks like.
     * @enum {string}
     */
    RunExportFormat: "csv" | "json";
    RunListResponse: {
      /**
       * @description How many rows are in `runs` (this page) -- distinct from `total`, the count of every
       *     run matching the filter across all pages.
       */
      returned: number;
      runs: components["schemas"]["RunSummaryResponse"][];
      /** Format: int64 */
      total: number;
    };
    /**
     * @description The final event emitted on every `GET /api/runs/{id}/stream` connection, named `done`,
     *     immediately before the stream closes. Deliberately carries only the outcome rather than
     *     duplicating the full run detail: the frontend already has `GET /api/runs/{id}` (via
     *     `useRun`) for the config/results/write-back-audit shape, so `done` just signals "stop
     *     listening and go refetch that" rather than growing this endpoint a second response shape.
     */
    RunStreamDone: {
      outcome: components["schemas"]["TuneOutcome"];
    };
    /**
     * @description One run in `GET /api/runs`'s `runs` array -- deliberately a subset matching the CLI's own
     *     `history list` table columns, not the full detail (that's [`RunDetailResponse`], for
     *     `GET /api/runs/{id}`).
     */
    RunSummaryResponse: {
      driver: components["schemas"]["TuneDriver"];
      /** Format: int64 */
      id: number;
      notes?: string | null;
      outcome: components["schemas"]["TuneOutcome"];
      process_type: components["schemas"]["ProcessType"];
      /** Format: date-time */
      started_at: string;
      tag_name: string;
    };
    /**
     * @description How much a [`TuneSampleRow`]'s `sample.pv` reading should be trusted, as recorded at the
     *     moment it was read (finding 5 of the live-plant safety review).
     *
     *     A `bhtune-db`-local mirror of [`bhtune_driver::Quality`], not a reuse of it directly:
     *     `bhtune-db` deliberately doesn't depend on `bhtune-driver` (a leaf I/O-adapter crate with
     *     a much heavier dependency tree -- `tokio`, `tonic`, `opcda-bridge` -- that has no business
     *     in the persistence crate just to name one three-variant enum), so `bhtune-cli`, which
     *     already depends on both, is the one place that converts between them. This mirrors
     *     [`TemplateOrigin`]'s own precedent: a small, persistence-local enum rather than a second
     *     dependency edge.
     * @enum {string}
     */
    SampleQuality: "good" | "uncertain" | "bad";
    /**
     * @description One recorded tick: the [`Tick`] input and resulting engine state, plus the driver-
     *     reported PV quality at read time. `Tick`/`MrftState` already derive `Serialize` in
     *     `bhtune-core` (they round-trip through golden-trace fixtures too), so they're embedded
     *     directly rather than re-projected field-by-field like the other DTOs here.
     */
    SampleResponse: {
      pv_quality: components["schemas"]["SampleQuality"];
      sample: components["schemas"]["Tick"];
      state: components["schemas"]["MrftState"];
      /** Format: int64 */
      tick_index: number;
    };
    /**
     * @description Advisory assessment of whether the recorded samples provide enough observations per
     *     oscillation period for a trustworthy extrema measurement.
     * @enum {string}
     */
    SamplingAdequacy: "adequate" | "marginal" | "not_assessed";
    /**
     * @description The body of `POST /api/runs` contains the per-run tune inputs. Operational timing values
     *     are intentionally absent: they are resolved from the global `[tuning]` configuration by
     *     `prepare()`, just as they are for a CLI invocation. Every field that has a CLI default
     *     (`--sim-gain`, etc.) repeats that exact default here via `#[serde(default = "...")]`, so an
     *     HTTP caller that omits a field gets identical behavior to a CLI invocation that omits the
     *     matching flag. `Option<T>` fields need no `#[serde(default)]` of their own -- serde already
     *     treats a missing key as `None` for an `Option` field.
     *
     *     Also derives `Serialize` so the exact same type can serve as `GET /api/runs/last-request`'s
     *     response (`ui-prefill-last-run`, in `routes::history::last_request`): that endpoint parses
     *     a run's stored `request_json` straight into a `StartRunRequest` rather than duplicating
     *     its ~30 fields into a second struct, giving a "what you `GET` is exactly what you'd `POST`
     *     to repeat it" symmetry in both the Rust types and the generated OpenAPI schema. This is
     *     safe precisely because `request_json` is *already* built to this exact shape --
     *     `bhtune-cli`'s `RequestSnapshot` doc comment describes the two as kept in sync by
     *     convention.
     */
    StartRunRequest: {
      /**
       * @description opcda-bridge gateway address. Only meaningful with `driver: "opcda"` (default:
       *     resolved the same way the CLI resolves `--bridge-host`, via this process's own
       *     config/env).
       */
      bridge_host?: string | null;
      controller_type: components["schemas"]["ControllerType"];
      /**
       * Format: int32
       * @description Relay cycles to count once the skip period ends (default: looked up per
       *     `process_type`).
       */
      cycles_count?: number | null;
      /**
       * Format: int32
       * @description Relay cycles to skip before counting begins (default: looked up per `process_type`).
       */
      cycles_skip?: number | null;
      direction?: null | components["schemas"]["ControllerDirection"];
      /**
       * @description Which driver drives this tune. `"replay"` is rejected -- that driver exists only
       *     for offline golden-trace validation, not for starting a live/simulated run.
       */
      driver: components["schemas"]["TuneDriver"];
      /**
       * Format: float
       * @description Fixed MV range high, overriding a live tag read.
       */
      mv_range_high?: number | null;
      /**
       * Format: float
       * @description Fixed MV range low, overriding a live tag read.
       */
      mv_range_low?: number | null;
      /**
       * Format: int32
       * @description Seconds a switch must persist before it's accepted (default: looked up per
       *     `process_type`).
       */
      noise_protection_secs?: number | null;
      /**
       * @description Operator notes to attach to this run. Notes can be edited or cleared later through
       *     the run-history endpoints.
       */
      notes?: string | null;
      process_type: components["schemas"]["ProcessType"];
      /**
       * Format: float
       * @description Fixed PV range high, overriding a live tag read. Required for `driver: "simulator"`,
       *     which has no range tags at all.
       */
      pv_range_high?: number | null;
      /**
       * Format: float
       * @description Fixed PV range low, overriding a live tag read.
       */
      pv_range_low?: number | null;
      /**
       * Format: float
       * @description Relay amplitude, as a percentage of the MV range.
       */
      relay_amp: number;
      /** @description OPC DA server ProgID. Required with `driver: "opcda"`. */
      server?: string | null;
      /**
       * Format: float
       * @description Simulator dead time, in seconds (`driver: "simulator"` only).
       */
      sim_dead_time?: number;
      /**
       * Format: float
       * @description Simulator process gain (`driver: "simulator"` only).
       */
      sim_gain?: number;
      /**
       * Format: float
       * @description Simulator initial MV (`driver: "simulator"` only).
       */
      sim_initial_mv?: number;
      /**
       * Format: float
       * @description Simulator initial PV (`driver: "simulator"` only).
       */
      sim_initial_pv?: number;
      /**
       * Format: float
       * @description Simulator measurement noise amplitude (`driver: "simulator"` only).
       */
      sim_noise?: number;
      /**
       * Format: int64
       * @description Simulator RNG seed, for reproducible noise (`driver: "simulator"` only).
       */
      sim_seed?: number;
      /**
       * Format: float
       * @description Simulator process time constant, in seconds (`driver: "simulator"` only).
       */
      sim_tau?: number;
      tag_overrides?: null | components["schemas"]["TagOverrides"];
      /** @description PV tag prefix; ignored for `driver: "simulator"`. See [`TuneArgs::tagname`]. */
      tagname: string;
      /** @description DCS/PLC template name (see `GET /api/templates`). */
      template: string;
      write_pid?: null | components["schemas"]["ResponseLevel"];
      /**
       * @description Confirm an unattended PID write-back. Required alongside `write_pid` -- the request
       *     is rejected otherwise, identically to `--write-pid` without `--yes` on the CLI.
       */
      yes?: boolean;
    };
    /**
     * @description Per-tune replacements for template-derived OPC tag names.
     *
     *     A missing or blank field keeps the active template's derived tag. The first eight fields
     *     replace template-derived tag names; the final five replace the tags used to read direction
     *     and range values. Fixed direction and range values remain separate `LoopTags` inputs and are
     *     applied after these read-tag overrides.
     */
    TagOverrides: {
      controller_direction?: string | null;
      controller_mode?: string | null;
      derivative_constant?: string | null;
      integral_constant?: string | null;
      lower_mv_range?: string | null;
      lower_pv_range?: string | null;
      manipulated_variable?: string | null;
      mode_attribute?: string | null;
      process_variable?: string | null;
      proportional_constant?: string | null;
      setpoint_variable?: string | null;
      upper_mv_range?: string | null;
      upper_pv_range?: string | null;
    };
    /**
     * @description Where a `dcs_templates` row came from, and -- since [`TuneRunRow`] snapshots a copy of one
     *     at [`TuneRunRow::start`] time -- where a run's snapshotted template came from too. Kept as
     *     one definition reused by both tables (`dcs_templates.origin`, `tune_runs.template_origin`)
     *     rather than two, so they can never drift on what the possible origins even are, and so a
     *     run's history never needs to look the original row back up to know its provenance --
     *     which matters precisely because that row might no longer exist, or might have been
     *     re-imported under a different origin since.
     *
     *     `builtin` and `catalog` rows are re-upserted from their respective data files on every
     *     startup ([`crate::seed::seed_templates`]); `user` rows (hand-imported via `bhtune template
     *     import`, or created through a future GUI editor) are never auto-touched -- auto-reseeding
     *     a hand-edited row would silently discard someone's own customization, while *not*
     *     reseeding a shipped preset would mean a suffix/unit fix in a later release never reaches
     *     existing installs.
     * @enum {string}
     */
    TemplateOrigin: "builtin" | "catalog" | "user";
    /**
     * @description The HTTP-facing shape of a stored template: the caller-supplied [`DcsTemplate`] fields
     *     flattened alongside the database-assigned `id`/`origin`/timestamps. Per this workspace's
     *     established DTO-decoupling convention (see `bhtune-cli`'s `commands::history` module doc
     *     comments), [`DcsTemplateRow`] itself deliberately does not derive `Serialize` -- every
     *     JSON-facing consumer builds its own projection rather than the DB row shape leaking
     *     straight onto the wire.
     */
    TemplateResponse: components["schemas"]["DcsTemplate"] & {
      /** Format: date-time */
      created_at: string;
      /** Format: int64 */
      id: number;
      origin: components["schemas"]["TemplateOrigin"];
      /** Format: date-time */
      updated_at: string;
    };
    /**
     * @description One PV sample fed into the engine. The engine has no clock of its own — every timestamp
     *     it ever reasons about arrives through a `Tick`.
     */
    Tick: {
      /** Format: float */
      pv: number;
      /** Format: date-time */
      time: string;
    };
    /**
     * @description The time unit a DCS expects for integral/derivative parameters.
     * @enum {string}
     */
    TimeUnit: "seconds" | "minutes";
    /**
     * @description The clock basis used for a run's persisted polling-cadence diagnostics.
     * @enum {string}
     */
    TimingBasis: "simulated_fixed_step" | "live_monotonic";
    /**
     * @description Polling-cadence diagnostics captured over one run's successful PV samples.
     *
     *     The two optional gap fields are `None` when fewer than two samples were observed. The
     *     measured oscillation fields are populated only for a completed MRFT run. Sampling adequacy
     *     is advisory metadata and does not determine calculated-result validity or write eligibility.
     */
    TimingMetrics: {
      /** Format: double */
      approximate_samples_per_period?: number | null;
      basis: components["schemas"]["TimingBasis"];
      /** Format: double */
      max_sample_gap_ms?: number | null;
      /** Format: double */
      mean_sample_gap_ms?: number | null;
      /** Format: double */
      measured_oscillation_period_ms?: number | null;
      /**
       * Format: int64
       * @description Number of adjacent sample gaps at least twice the requested interval. Each such gap
       *     proves that at least one complete polling opportunity was missed.
       */
      missed_poll_opportunity_count: number;
      poll_latency?: null | components["schemas"]["PollLatencyMetrics"];
      /** Format: int64 */
      requested_interval_ms: number;
      /** Format: int64 */
      sample_gap_count: number;
      /**
       * @description Assessment uses the observed samples-per-period value and a six-sample advisory
       *     threshold. Old timing snapshots deserialize as `not_assessed`.
       */
      sampling_adequacy?: components["schemas"]["SamplingAdequacy"];
    };
    /** @description Summary statistics for one class of measured polling work. */
    TimingSummary: {
      /** Format: int64 */
      count: number;
      /** Format: double */
      max_ms?: number | null;
      /** Format: double */
      mean_ms?: number | null;
    };
    /**
     * @description Which [`crate`]-agnostic I/O driver a run used. Lives in `bhtune-db` rather than
     *     `bhtune-core` because it's a persistence/orchestration concept (which adapter drove this
     *     run), not a domain concept the pure MRFT engine itself needs to know about.
     * @enum {string}
     */
    TuneDriver: "opcda" | "simulator" | "replay";
    /**
     * @description A run's lifecycle state.
     * @enum {string}
     */
    TuneOutcome: "running" | "completed" | "failed" | "aborted";
    /**
     * @description Why a calculated response-level result was marked invalid.
     * @enum {string}
     */
    TuningResultInvalidReason:
      | "non_finite_pv_amplitude"
      | "non_positive_pv_amplitude"
      | "non_finite_period"
      | "non_positive_period"
      | "non_finite_frequency"
      | "non_positive_frequency"
      | "non_finite_kp"
      | "non_finite_ti_minutes"
      | "non_finite_td_minutes"
      | "non_finite_proportional"
      | "non_finite_integral"
      | "non_finite_derivative";
    /**
     * @description Whether a calculated response-level result contains values that are safe to use.
     * @enum {string}
     */
    TuningResultStatus: "valid" | "invalid";
    UpdateConfigRequest: {
      allow_uncertain_quality: boolean;
      /** Format: int32 */
      retention_days?: number | null;
      revision: string;
      tuning?: null | components["schemas"]["UpdateTuningRequest"];
    };
    /** @description The body of `PUT /api/runs/{id}/notes`. */
    UpdateNotesRequest: {
      /** @description Replacement note text. Blank or whitespace-only text clears the note. */
      notes: string;
    };
    UpdateTuningRequest: {
      /** Format: int32 */
      mrft_delay_secs?: number | null;
      /** Format: int64 */
      op_timeout_secs?: number | null;
      /** Format: int64 */
      poll_interval_ms?: number | null;
      /** Format: int64 */
      restore_timeout_secs?: number | null;
      /** Format: int64 */
      timeout_secs?: number | null;
    };
    /**
     * @description Distinguishes a normal write-back from `bhtune history revert` undoing an earlier one.
     *     Both share [`TuneWriteRow`]'s exact shape -- pre-read, write-and-verify each constant,
     *     audit the outcome -- so they live in the same table rather than a second near-duplicate
     *     one; `kind` is the one column that tells them apart.
     * @enum {string}
     */
    WriteKind: "write" | "revert";
    /** @description Local projection of [`TuneWriteRow`]. */
    WriteResponse: {
      allow_uncertain_quality: boolean;
      /** Format: float */
      derivative_previous?: number | null;
      /** Format: float */
      derivative_readback?: number | null;
      /** Format: float */
      derivative_written?: number | null;
      error_message?: string | null;
      /** Format: float */
      integral_previous?: number | null;
      /** Format: float */
      integral_readback?: number | null;
      /** Format: float */
      integral_written?: number | null;
      kind: components["schemas"]["WriteKind"];
      /** Format: float */
      proportional_previous?: number | null;
      /** Format: float */
      proportional_readback?: number | null;
      /** Format: float */
      proportional_written?: number | null;
      response_level: components["schemas"]["ResponseLevel"];
      rollback_error?: string | null;
      rollback_state?: null | components["schemas"]["RollbackState"];
      success: boolean;
      /** Format: date-time */
      written_at: string;
    };
    /** @description The body of `POST /api/runs/{id}/write`. */
    WriteRunRequest: {
      /** @description Which of the run's three calculated candidate result sets to write. */
      response_level: components["schemas"]["ResponseLevel"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_config: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The TOML and effective global configuration. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigResponse"];
        };
      };
      /** @description The configuration store could not be read. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  put_config: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateConfigRequest"];
      };
    };
    responses: {
      /** @description The configuration was saved. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigResponse"];
        };
      };
      /** @description The request contains an invalid retention or tuning policy. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The supplied revision is stale or the file changed on disk. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The configuration could not be written. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The process is up and answering HTTP, with its application version. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  browse: {
    parameters: {
      query?: {
        bridge_host?: string;
        opc_server?: string;
        /**
         * @description The tree level to list; an absent or empty path lists the top level, matching
         *     `Driver::browse`'s own "empty string for the top level" convention.
         */
        path?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OpcBrowseResponse"];
        };
      };
      /** @description No OPC server was specified (and none is configured), or the gateway/browse call could not be reached in time. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  read: {
    parameters: {
      query?: {
        bridge_host?: string;
        opc_server?: string;
        /**
         * @description The fully qualified tag to read (e.g. `"Unit1.LIC101.PV"`). Required -- unlike the
         *     other two fields, there is no configured default for "which tag".
         */
        tag?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OpcReadResponse"];
        };
      };
      /** @description No tag or OPC server was specified (and none is configured), or the gateway/read call could not be reached in time. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  servers: {
    parameters: {
      query?: {
        /**
         * @description Overrides the configured/default bridge host for this one request, matching `bhtune
         *     opc servers --bridge-host`.
         */
        bridge_host?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OpcServersResponse"];
        };
      };
      /** @description The bridge gateway could not be reached in time. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  list_runs: {
    parameters: {
      query?: {
        loop_id?: number;
        process_type?: components["schemas"]["ProcessType"];
        controller_type?: components["schemas"]["ControllerType"];
        outcome?: components["schemas"]["TuneOutcome"];
        driver?: components["schemas"]["TuneDriver"];
        started_after?: string;
        started_before?: string;
        template_name?: string;
        template_origin?: components["schemas"]["TemplateOrigin"];
        /**
         * @description Filters on the run's recorded, *resolved* OPC server (`db-run-request-snapshot`) --
         *     always absent for a simulator/replay run, so this filter alone never matches one.
         */
        opc_server?: string;
        /** @description Filters on the run's recorded, resolved bridge host, matching `opc_server` above. */
        bridge_host?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of runs matching the filter. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunListResponse"];
        };
      };
    };
  };
  start_run: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartRunRequest"];
      };
    };
    responses: {
      /** @description The run was started; detail reflects its state right now. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetailResponse"];
        };
      };
      /** @description The request failed validation, or `prepare()` itself failed (unknown template, invalid flag combination, unreachable driver). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description An exclusive PID write/revert is already active. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_draft: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The saved New Tune draft, or null when none exists. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": null | components["schemas"]["NewRunDraft"];
        };
      };
      /** @description The stored draft is malformed or the database failed. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  put_draft: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewRunDraft"];
      };
    };
    responses: {
      /** @description The draft was saved. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NewRunDraft"];
        };
      };
      /** @description The database failed or the draft could not be stored. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  last_request: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The newest run's original request, or `null` if no runs exist yet or its request isn't usable. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": null | components["schemas"]["StartRunRequest"];
        };
      };
    };
  };
  show_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The full recorded detail for one run. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetailResponse"];
        };
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  delete_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Run deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The run has not finished yet. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  cancel_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation requested (or the run was already inactive). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  export_run: {
    parameters: {
      query?: {
        /** @description Defaults to `csv` when omitted, matching `bhtune export`'s own CLI default. */
        format?: components["schemas"]["RunExportFormat"];
      };
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The run's recorded samples, as CSV (default) or JSON. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/csv": unknown;
        };
      };
      /** @description No run with that id, or it has no recorded samples. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  update_notes: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateNotesRequest"];
      };
    };
    responses: {
      /** @description The run with its updated notes. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetailResponse"];
        };
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  delete_notes: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The run with its notes cleared. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetailResponse"];
        };
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  revert_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The revert was attempted; see `writes[]` in the body for its outcome. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetailResponse"];
        };
      };
      /** @description The run isn't eligible for a post-hoc revert (still running, wrong driver, no PID tags/connection recorded, no recorded write-back to revert, or its pre-write values were never recorded), or the driver connection itself failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description A tune or another PID write/revert is already active. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  stream_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A `text/event-stream` with an optional `initial` event (data: InitialReadingsResponse), `sample` events (data: SampleResponse), and one final `done` event (data: RunStreamDone). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": components["schemas"]["SampleResponse"];
        };
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  write_run: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Run id */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteRunRequest"];
      };
    };
    responses: {
      /** @description The write was attempted; see `writes[]` in the body for its outcome. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetailResponse"];
        };
      };
      /** @description The run isn't eligible for a post-hoc write (still running, wrong driver, no PID tags/connection recorded, or no calculated result for the requested response level), or the driver connection itself failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description No run with that id. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description A tune or another PID write/revert is already active. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  list_templates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Every stored template, ordered by name. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateResponse"][];
        };
      };
    };
  };
  create_template: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DcsTemplate"];
      };
    };
    responses: {
      /** @description Template created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateResponse"];
        };
      };
      /** @description The template failed validation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description A template with this name already exists. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateResponse"];
        };
      };
      /** @description No template with that name. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  update_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template name */
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DcsTemplate"];
      };
    };
    responses: {
      /** @description Template updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TemplateResponse"];
        };
      };
      /** @description The template failed validation, or its name doesn't match the path. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description No template with that name. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The template isn't user-owned and can't be edited over HTTP. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  delete_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Template name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Template deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No template with that name. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description The template is still referenced by one or more saved loops. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
}
