# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_bhtune_global_optspecs
    string join \n config= db= templates= log-level= log-dir= log-format= log-rotation= h/help V/version
end

function __fish_bhtune_needs_command
    # Figure out if the current invocation already has a command.
    set -l cmd (commandline -opc)
    set -e cmd[1]
    argparse -s (__fish_bhtune_global_optspecs) -- $cmd 2>/dev/null
    or return
    if set -q argv[1]
        # Also print the command, so this can be used to figure out what it is.
        echo $argv[1]
        return 1
    end
    return 0
end

function __fish_bhtune_using_subcommand
    set -l cmd (__fish_bhtune_needs_command)
    test -z "$cmd"
    and return 1
    contains -- $cmd[1] $argv
end

complete -c bhtune -n "__fish_bhtune_needs_command" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_needs_command" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_needs_command" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_needs_command" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_needs_command" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_needs_command" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_needs_command" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_needs_command" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_needs_command" -s V -l version -d 'Print version'
complete -c bhtune -n "__fish_bhtune_needs_command" -f -a "tune" -d 'Run an MRFT tune against a real OPC DA loop or the in-process simulator'
complete -c bhtune -n "__fish_bhtune_needs_command" -f -a "simulate" -d 'Run a zero-configuration demo MRFT tune against the built-in FOPDT simulator'
complete -c bhtune -n "__fish_bhtune_needs_command" -f -a "template" -d 'Inspect and manage DCS/PLC templates'
complete -c bhtune -n "__fish_bhtune_needs_command" -f -a "history" -d 'Inspect past tune runs'
complete -c bhtune -n "__fish_bhtune_needs_command" -f -a "export" -d 'Export one run\'s recorded samples as CSV or JSON'
complete -c bhtune -n "__fish_bhtune_needs_command" -f -a "opc" -d 'Low-level OPC DA passthrough (diagnostics) via the opcda-bridge gateway, bypassing the tuning engine entirely'
complete -c bhtune -n "__fish_bhtune_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -s t -l tagname -d 'PV tag prefix; the rest of the tag set is derived from it using `--template`\'s suffix convention. Ignored for `--backend simulator`, which uses two fixed internal tag names instead' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l template -d 'DCS/PLC template name (see `bhtune template list`)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l process-type -r -f -a "flow\t''
pressure-line\t''
pressure-vessel\t''
level\t''
temperature-mixing\t''
temperature-heat-exchange\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l controller-type -r -f -a "p\t''
pi\t''
pid\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l relay-amp -d 'Relay amplitude, as a percentage of the MV range' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l cycles-skip -d 'Relay cycles to skip before counting begins (default: looked up per `--process-type`)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l cycles-count -d 'Relay cycles to count once the skip period ends (default: looked up per `--process-type`)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l noise-protection-secs -d 'Seconds a switch must persist before it\'s accepted (default: looked up per `--process-type`)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l mrft-delay -d 'Pre/post-test recording padding, in seconds (legacy: `--mrftDelayTime`)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l backend -d 'Which backend drives this tune' -r -f -a "opcda\t'A real OPC DA server, reached through an opcda-bridge gateway'
simulator\t'The in-process FOPDT simulator — no external dependency at all'"
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l bridge-host -d 'opcda-bridge gateway address. bhtune connects to the bridge gateway rather than a DCOM host directly — see AGENTS.md\'s OPC DA integration notes. Only meaningful with `--backend opcda` (default: `crate::config::DEFAULT_BRIDGE_HOST`, overridable via the `BHTUNE_BRIDGE_HOST` env var or the config file\'s `bridge_host` key)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l server -d 'OPC DA server ProgID (legacy: `-s`/`--opcServerID`). Required with `--backend opcda`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l sim-gain -d 'Simulator process gain (`--backend simulator` only)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l sim-tau -d 'Simulator process time constant, in seconds (`--backend simulator` only)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l sim-dead-time -d 'Simulator dead time, in seconds (`--backend simulator` only)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l sim-noise -d 'Simulator measurement noise amplitude (`--backend simulator` only)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l sim-seed -d 'Simulator RNG seed, for reproducible noise (`--backend simulator` only)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l sim-initial-pv -d 'Simulator initial PV (`--backend simulator` only)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l sim-initial-mv -d 'Simulator initial MV (`--backend simulator` only)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l pv-range-high -d 'Fixed PV range high, overriding a live tag read (legacy: the PV range "toggle tag/value" button). Required (defaults to 100.0) for `--backend simulator`, which has no range tags at all' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l pv-range-low -d 'Fixed PV range low, overriding a live tag read' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l mv-range-high -d 'Fixed MV range high, overriding a live tag read' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l mv-range-low -d 'Fixed MV range low, overriding a live tag read' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l direction -d 'Fixed controller direction, overriding a live tag read' -r -f -a "direct\t''
reverse\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l poll-interval-ms -d 'How often to poll the backend, in milliseconds (legacy: the 800 ms WinForms timer)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l timeout-secs -d 'Hard wall-clock cap on this run\'s total duration (including any `--mrft-delay` padding), in seconds. If the engine hasn\'t reported completion by the deadline, the run is aborted and the loop is automatically restored, exactly like Ctrl+C -- but with no one present to press it. Always enforced; there is no way to disable it, since an unattended run must never be able to perturb a live process indefinitely. Size this to comfortably exceed your slowest loop\'s expected test duration -- temperature loops in particular can need much longer than the default' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l name -d 'A friendly name for this run, recorded as `loop_name` (default: the PV tag name)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l write-pid -d 'Non-interactively write this response level\'s calculated PID parameters back to the DCS instead of prompting on stdin -- the flag that makes a scheduled/scripted tune able to actually update a loop with no one watching. Requires `--yes`' -r -f -a "aggressive\t''
moderate\t''
sluggish\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l op-timeout-secs -d 'Cap on any single backend read/write during the run, in seconds. A stalled call (gateway down, DCOM wedged, network black-holed) is abandoned rather than awaited forever once this elapses, so Ctrl+C and `--timeout-secs` both stay effective even mid-hung-read/write -- see AGENTS.md\'s `safety-cancellation` section. Distinct from `--timeout-secs`, which bounds the whole run rather than one operation; size this well above a healthy round trip to your OPC DA gateway, not to the expected test duration' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l restore-timeout-secs -d 'Cap on restoring the loop to its pre-test mode/MV/setpoint after the run ends (by completion, Ctrl+C, or a timeout), in seconds. Bounded independently of `--timeout-secs`, since a restore triggered *by* a timeout would otherwise inherit an already-expired budget. If this elapses (or a second Ctrl+C arrives first), the run exits `EXIT_RESTORE_INCOMPLETE` with a warning naming the loop and its last-written value, instead of hanging indefinitely' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l output -d 'How to print this run\'s final outcome line' -r -f -a "table\t'Human-readable text (default)'
json\t'Pretty-printed JSON. This is the external contract for scripted/scheduled consumers, so its shape must not change silently once shipped'"
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l yes -d 'Confirm an unattended PID write-back. Required alongside `--write-pid` -- the command refuses to start otherwise -- since writing to a live loop with no human present must be an explicit, deliberate choice. Has no effect without `--write-pid`'
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -l allow-uncertain-quality -d 'Accept `Quality::Uncertain` OPC readings instead of hard-failing on them. Off by default: a stale/held value is indistinguishable from a live one to the MRFT engine, so tolerating it can silently corrupt the switch-period measurement the whole test depends on. Only for sites whose gateway reports `Uncertain` as a matter of course -- `Quality::Bad` is never accepted, with or without this flag. Logged loudly when used and recorded on the run (`tune_runs.allow_uncertain_quality`), so history shows a run executed under relaxed rules'
complete -c bhtune -n "__fish_bhtune_using_subcommand tune" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -s t -l tagname -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l template -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l process-type -r -f -a "flow\t''
pressure-line\t''
pressure-vessel\t''
level\t''
temperature-mixing\t''
temperature-heat-exchange\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l controller-type -r -f -a "p\t''
pi\t''
pid\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l relay-amp -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l cycles-skip -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l cycles-count -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l noise-protection-secs -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l mrft-delay -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l sim-gain -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l sim-tau -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l sim-dead-time -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l sim-noise -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l sim-seed -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l sim-initial-pv -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l sim-initial-mv -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l poll-interval-ms -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l timeout-secs -d 'See `TuneArgs::timeout_secs`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l name -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l write-pid -d 'See `TuneArgs::write_pid`. Note the built-in FOPDT simulator has no PID constant tags at all (see `build_loop_tags`), so write-back is always skipped for `simulate` regardless of this flag -- it\'s accepted here purely so `simulate`\'s flag surface stays a strict defaulted subset of `tune`\'s, matching every other field' -r -f -a "aggressive\t''
moderate\t''
sluggish\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l op-timeout-secs -d 'See `TuneArgs::op_timeout_secs`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l restore-timeout-secs -d 'See `TuneArgs::restore_timeout_secs`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l output -d 'See `TuneArgs::output`' -r -f -a "table\t'Human-readable text (default)'
json\t'Pretty-printed JSON. This is the external contract for scripted/scheduled consumers, so its shape must not change silently once shipped'"
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l yes -d 'See `TuneArgs::yes`'
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -l allow-uncertain-quality -d 'See `TuneArgs::allow_uncertain_quality`'
complete -c bhtune -n "__fish_bhtune_using_subcommand simulate" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -f -a "list" -d 'List every template (built-in and user-imported)'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -f -a "show" -d 'Show one template\'s full detail as JSON'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -f -a "import" -d 'Import a template from a file. Accepts either a single template as JSON (see `template export`\'s default output shape) or a multi-template TOML catalog (the same `[[template]]` array-of-tables shape as the embedded/user catalog, see `template export --format toml`) -- the format is auto-detected from the file\'s content, not its extension. A JSON single-template import is rejected outright if a template with that name already exists; a TOML catalog import instead skips (and reports) any template whose name already exists, so re-importing an updated community catalog only adds what\'s new'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -f -a "export" -d 'Export a template to a file, e.g. as a starting point for a site-specific copy or a community catalog contribution'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -f -a "delete" -d 'Delete a template. Refuses if any saved loop still references it. A `Builtin`- or `Catalog`-origin template reappears automatically the next time bhtune starts unless it\'s also removed from its source (bhtune-core\'s embedded catalog for `Builtin`, which only a new bhtune release can change; the user catalog file for `Catalog`)'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and not __fish_seen_subcommand_from list show import export delete help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from list" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from list" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from list" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from list" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from list" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from list" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from list" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from show" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from show" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from show" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from show" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from show" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from show" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from show" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from import" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from import" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from import" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from import" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from import" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from import" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from import" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from import" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -l format -d 'File format to write. `toml` emits a single-entry `[[template]]` catalog block, ready to paste into a catalog file or open as a contribution pull request' -r -f -a "json\t''
toml\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from export" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from delete" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from delete" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from delete" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from delete" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from delete" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from delete" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from delete" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "list" -d 'List every template (built-in and user-imported)'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show one template\'s full detail as JSON'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "import" -d 'Import a template from a file. Accepts either a single template as JSON (see `template export`\'s default output shape) or a multi-template TOML catalog (the same `[[template]]` array-of-tables shape as the embedded/user catalog, see `template export --format toml`) -- the format is auto-detected from the file\'s content, not its extension. A JSON single-template import is rejected outright if a template with that name already exists; a TOML catalog import instead skips (and reports) any template whose name already exists, so re-importing an updated community catalog only adds what\'s new'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "export" -d 'Export a template to a file, e.g. as a starting point for a site-specific copy or a community catalog contribution'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete a template. Refuses if any saved loop still references it. A `Builtin`- or `Catalog`-origin template reappears automatically the next time bhtune starts unless it\'s also removed from its source (bhtune-core\'s embedded catalog for `Builtin`, which only a new bhtune release can change; the user catalog file for `Catalog`)'
complete -c bhtune -n "__fish_bhtune_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -f -a "list" -d 'List past runs, newest first'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -f -a "show" -d 'Show one run\'s full detail: config, initial readings, calculated results, and any PID write-back audit rows'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -f -a "revert" -d 'Undo a run\'s PID write-back, writing its recorded pre-write P/I/D values back to the live loop. Reverts whichever `write`-kind write-back that run last recorded; refuses if the run has none, if that write-back\'s pre-read itself failed (nothing to revert to), or if the run did not use the `opcda` backend (nothing live to revert against)'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and not __fish_seen_subcommand_from list show revert help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l outcome -r -f -a "running\t''
completed\t''
failed\t''
aborted\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l limit -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l offset -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l output -d 'How to print the run list' -r -f -a "table\t'Human-readable text (default)'
json\t'Pretty-printed JSON. This is the external contract for scripted/scheduled consumers, so its shape must not change silently once shipped'"
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -l output -d 'How to print the run detail' -r -f -a "table\t'Human-readable text (default)'
json\t'Pretty-printed JSON. This is the external contract for scripted/scheduled consumers, so its shape must not change silently once shipped'"
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l bridge-host -d '(default: `crate::config::DEFAULT_BRIDGE_HOST`, overridable via `BHTUNE_BRIDGE_HOST` or the config file\'s `bridge_host` key.)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l server -d '(default: the config file\'s `server` key; errors if neither is set.)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l output -d 'How to print the revert outcome' -r -f -a "table\t'Human-readable text (default)'
json\t'Pretty-printed JSON. This is the external contract for scripted/scheduled consumers, so its shape must not change silently once shipped'"
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -l yes -d 'Confirm writing to a live loop. Required -- there is no interactive prompt for reverting, since there is no calculated result to choose between as there is for `tune`\'s own write-back step'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from revert" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from help" -f -a "list" -d 'List past runs, newest first'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show one run\'s full detail: config, initial readings, calculated results, and any PID write-back audit rows'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from help" -f -a "revert" -d 'Undo a run\'s PID write-back, writing its recorded pre-write P/I/D values back to the live loop. Reverts whichever `write`-kind write-back that run last recorded; refuses if the run has none, if that write-back\'s pre-read itself failed (nothing to revert to), or if the run did not use the `opcda` backend (nothing live to revert against)'
complete -c bhtune -n "__fish_bhtune_using_subcommand history; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l format -r -f -a "csv\t''
json\t''"
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l output -d 'Output file path (default: stdout)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand export" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -f -a "read" -d 'Read one or more tags'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -f -a "write" -d 'Write a value to one tag'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -f -a "browse" -d 'Browse tags under a path (empty for the top level)'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and not __fish_seen_subcommand_from read write browse help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l bridge-host -d '(default: `crate::config::DEFAULT_BRIDGE_HOST`, overridable via `BHTUNE_BRIDGE_HOST` or the config file\'s `bridge_host` key.)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l server -d '(default: the config file\'s `server` key; errors if neither is set.)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from read" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l bridge-host -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l server -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from write" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l bridge-host -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l server -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l config -d 'Path to a TOML config file (default: platform-specific, see `crate::config`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l db -d 'Path to the SQLite database file (default: a platform-standard data directory, see `crate::config::default_db_path_from`). CLI > `BHTUNE_DB` env var > `db` in the config file > platform default -- see `crate::config::resolve_db_path`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l templates -d 'Path to a user-supplied DCS/PLC template catalog, auto-loaded on every startup in addition to the built-in templates (default: platform-specific, next to the config file -- see `crate::config::templates_path_from`). A missing file at the default location is fine; a file that fails to parse or validate is a hard error. CLI > `BHTUNE_TEMPLATES` env var > `templates` in the config file > platform default -- see `crate::config::load_user_templates`' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l log-level -d 'Log level / directive spec, e.g. "info" or "bhtune_cli=debug,sqlx=warn" (default: info). Diagnostic detail only -- never printed to stdout, so it can never interleave with `--output json`\'s single-object contract; see `crate::logging`' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l log-dir -d 'Directory to write log files to (default: a platform-standard data directory, see `crate::config::default_log_dir_from`)' -r -F
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l log-format -d 'Log file format: "pretty" or "json" (default: pretty)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -l log-rotation -d 'Log file rotation: "hourly", "daily", or "never" (default: daily)' -r
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from browse" -s h -l help -d 'Print help'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from help" -f -a "read" -d 'Read one or more tags'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from help" -f -a "write" -d 'Write a value to one tag'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from help" -f -a "browse" -d 'Browse tags under a path (empty for the top level)'
complete -c bhtune -n "__fish_bhtune_using_subcommand opc; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and not __fish_seen_subcommand_from tune simulate template history export opc help" -f -a "tune" -d 'Run an MRFT tune against a real OPC DA loop or the in-process simulator'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and not __fish_seen_subcommand_from tune simulate template history export opc help" -f -a "simulate" -d 'Run a zero-configuration demo MRFT tune against the built-in FOPDT simulator'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and not __fish_seen_subcommand_from tune simulate template history export opc help" -f -a "template" -d 'Inspect and manage DCS/PLC templates'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and not __fish_seen_subcommand_from tune simulate template history export opc help" -f -a "history" -d 'Inspect past tune runs'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and not __fish_seen_subcommand_from tune simulate template history export opc help" -f -a "export" -d 'Export one run\'s recorded samples as CSV or JSON'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and not __fish_seen_subcommand_from tune simulate template history export opc help" -f -a "opc" -d 'Low-level OPC DA passthrough (diagnostics) via the opcda-bridge gateway, bypassing the tuning engine entirely'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and not __fish_seen_subcommand_from tune simulate template history export opc help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from template" -f -a "list" -d 'List every template (built-in and user-imported)'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from template" -f -a "show" -d 'Show one template\'s full detail as JSON'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from template" -f -a "import" -d 'Import a template from a file. Accepts either a single template as JSON (see `template export`\'s default output shape) or a multi-template TOML catalog (the same `[[template]]` array-of-tables shape as the embedded/user catalog, see `template export --format toml`) -- the format is auto-detected from the file\'s content, not its extension. A JSON single-template import is rejected outright if a template with that name already exists; a TOML catalog import instead skips (and reports) any template whose name already exists, so re-importing an updated community catalog only adds what\'s new'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from template" -f -a "export" -d 'Export a template to a file, e.g. as a starting point for a site-specific copy or a community catalog contribution'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from template" -f -a "delete" -d 'Delete a template. Refuses if any saved loop still references it. A `Builtin`- or `Catalog`-origin template reappears automatically the next time bhtune starts unless it\'s also removed from its source (bhtune-core\'s embedded catalog for `Builtin`, which only a new bhtune release can change; the user catalog file for `Catalog`)'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from history" -f -a "list" -d 'List past runs, newest first'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from history" -f -a "show" -d 'Show one run\'s full detail: config, initial readings, calculated results, and any PID write-back audit rows'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from history" -f -a "revert" -d 'Undo a run\'s PID write-back, writing its recorded pre-write P/I/D values back to the live loop. Reverts whichever `write`-kind write-back that run last recorded; refuses if the run has none, if that write-back\'s pre-read itself failed (nothing to revert to), or if the run did not use the `opcda` backend (nothing live to revert against)'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from opc" -f -a "read" -d 'Read one or more tags'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from opc" -f -a "write" -d 'Write a value to one tag'
complete -c bhtune -n "__fish_bhtune_using_subcommand help; and __fish_seen_subcommand_from opc" -f -a "browse" -d 'Browse tags under a path (empty for the top level)'
