import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The whole sidebar is generated from docs/'s own folder structure and each
// file's `sidebar_position` front matter / each folder's `_category_.json` --
// see docs/getting-started/_category_.json etc. There is deliberately no
// hand-maintained list here to keep in sync as pages are added.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
